// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://difcwhbqumzrzmputojb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpZmN3aGJxdW16cnptcHV0b2piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NDk2NzUsImV4cCI6MjA3MTUyNTY3NX0.bm5g3hXgZoYyge3RYWqk3mazYUehlzdcxLaQt9l7xsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});